version: '3.1'

services:

  mysqlhost:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
       - 3306:3306
    volumes:
      - "./mysql/config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./mysql/data:/var/lib/mysql:rw"
      
  mongohost:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
        
  patienthost:
    image: mediscreen/patient
    ports:
      - 8081:8080
    restart: always
    environment:
      mysqlhost: mysqlhost:3306
      
  uihost:
    image: mediscreen/ui
    volumes:
      - '../mediscreen-ui/:/app'
      - '/app/node_modules'
    ports:
      - 4201:4200
    environment:
      patienthost: patienthost

