version: '3.1'

services:

services:

  mysqlhost:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
       - 3306:3306
    volumes:
      - "./mysql/config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./mysql/data:/var/lib/mysql:rw"
      
  mongohost:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./mongodb/data:/data:rw"
      
        
  patienthost:
    image: mediscreen-patient
    ports:
      - 8081:8080
    restart: always
    
      
  notehost:
    image: mediscreen-note
    ports:
      - 8082:8080
    restart: always
    
  diabetesiahost:
    image: mediscreen-diabetesia
    ports:
      - 8083:8080
    restart: always
      
  uihost:
    image: mediscreen-ui
    ports:
      - 4200:80
    restart: always

